---

# This file is used to manage default variables for all hosts in the environment

# Package settings
# Packages that should be installed and up-to-date
packagesToInstall: ['screen', 'vi', 'vim', 'audit', 'rkhunter', 'awscli', 'collectd', 'policycoreutils-python', 'polkit', 'jq']

# Packages that should not be installed
packagesToRemove: ['rsh', 'rlogin', 'rcp', 'ypserv', 'ypbind', 'tftp', 'tftp-server', 'talk', 'talk-server', 'ftp', 'ftp-server', '@X Window System', 'ebtables', 'fail2ban', 'fail2ban-firewalld', 'fail2ban-server', 'fail2ban-sendmail', 'iptables']

# Services that should be enabled to start on startup
servicesToEnable: ['auditd']

# Services that should be disabled from starting
servicesToDisable: []

# Software configuration settings
# SSH Settings that should be present, and absent in the SSH config file
sshSettingsPresent: ['Protocol 2', 'LogLevel VERBOSE' , 'PermitRootLogin no' , 'PermitEmptyPasswords no', 'MaxAuthTries 3', 'X11Forwarding no', 'banner /etc/banner']
sshSettingsAbsent: ['X11Forwarding yes']