---

- name: Create Portainer Data Volume
  docker_volume:
    name: portainerData

- name: Manage Portainer Image
  docker_image:
    state: present
    name: portainer/portainer
    force_source: yes
    source: pull

- name: Create Portainer Container
  docker_container:
    detach: true
    name: portainer
    image: portainer/portainer
    labels:
      traefik.http.routers.portainer.tls: "true"
    log_driver: splunk
    log_options:
      splunk-token: "{{ splunkContainerHECToken }}"
      splunk-url: https://splunk.greentangent.net:8088
      splunk-insecureskipverify: true
      splunk-index: containers
      splunk-source: portainer
      splunk-sourcetype: syslog
      splunk-verify-connection: false
    state: started
    restart_policy: unless-stopped
    privileged: true
    published_ports:
      - 9002:9000
    volumes:
      - portainerData:/data
      - /var/run/docker.sock:/var/run/docker.sock
